version: '3.5'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - pgdata003:/var/lib/postgresql/data
    ports:
      - '5433:5432'
  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v5
    volumes:
      - ./config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - 8001:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
 
  caddy:
    image: caddy:latest
    ports:
      - '81:80'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile  # Mount the Caddyfile
    depends_on:
      - mercure
  # minio:
  #   image: docker.io/bitnami/minio:2022
  #   environment:
  #     MINIO_ROOT_USER: anto
  #     MINIO_ROOT_PASSWORD: anto19#00
  #   ports:
  #     - '9000:9000'
  #     - '9001:9001'
  #   volumes:
  #     - 'minio_data:/data'
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: VS_Container
    ports:
      - '3001:3001'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=marvinndg242@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=anto19998
    ports:
      - '5050:80'
    depends_on:
      - db
volumes:
  pgdata003:
  minio_data:
