version: '3.5'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - pgdata003:/var/lib/postgresql/data
    ports:
      - '5433:5432'
  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v5
    volumes:
      - ./config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - 8001:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: VS_Container
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

volumes:
  pgdata003:
  minio_data:
